.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/general-issue-template.md, .github/PULL_REQUEST_TEMPLATE.md
Foi criado um template para issues gerais e um para bugs, além disso também foi deletada a pasta da tentativa anterior de criar tais templates e alterado o template de pull request.
#6 Criar templates de Issues e Pull Requests
-
-
* Criado os templates de bug e geral.
* Excluída pasta feita anteriormente.
* Alterado template de pull request para não ser mais necessário relacionar com outro pull request.
=> Atualizando issue templates

docs/documentacao/documento-de-visao.md, mkdocs.yml
Foi criado o documento de visão e upado para o github page, o conteúdo contido no documento foi decidido por toda a equipe através de um doc compartilhado.
Co-authored-by: Roberto <robertosantana2001@gmail.com>
#21 Abertura do documento de Visão
Os testes foram feitos por meio de pareamento usando o mkdocs serve.
* Abertura do Documento de Visão
* Upando o Documento de Visão para a wiki
=> Criando documento de visao

docs/documentacao/documento-de-arquitetura.md, mkdocs.yml
- Adição do Documento de Visão na pasta /docs/documentacao
- Modificação do arquivo mkdcos.yml.
Co-authored-by: Rafael <rafael.cleydson@gmail.com>
#25 Abertura do Documento de Arquitetura
- Foi testado com o mkdocs serve em pareamento de Roberto e Rafael.
* Criação do Documento de Arquitetura em markDown;
* Upar ele para github Page
=> Adicionando Documento de Arquitetura na Wiki

docs/documentacao/roadmap.md, mkdocs.yml
Foi aberto a aba de Roadmap na wiki, contendo as issues que foram realizadas em cada sprint até agora e vai ser atualizada semanalmente.
#29 Criação de documento do Roadmap
Os testes foram feitos por meio de pareamento usando o mkdocs serve.
* Abertura do Roadmap 
* Upar o Roadmap na wiki
=> Adicionando o Roadmap na wiki

docs/documentacao/documento-de-metodologias.md, mkdocs.yml
Neste PR contém o documento de metodologias, o qual contempla um breve resumo sobre as metodologias usadas durante o desenvolvimento do nosso projeto, estando sujeito a mudanças e atualizações, porém por enquanto está funcional !
#43 Criar documento de metodologias
Todos os testes foram feitos por meio do mkdocs serve de acordo com a necessidade, sendo aplicado o pareamento nos testes finais.
* Criação do Documento de metodologias
* Documentação funcionando na Wiki
=> #43 Criado o Documento de Metodologia utilizadas

docs/documentacao/documento-de-arquitetura.md
Foi adicionado ao tópico React as principais funcionalidades dessa biblioteca e o porque iremos utilizá-la em nosso front-end.
#40
Foi testado utilizando a ferramenta "mkdocs serve" do mkdocs.
* Adicionado o texto sobre React no documento de arquitetura
* Adicionado as principais funcionalidades do React
=> Adicionando o tópico React no documento de arquitetura

docs/CODE_OF_CONDUCT.md, docs/como_contribuir.md, docs/policies/branches.md, docs/policies/commits.md, docs/policies/issues.md, docs/policies/pullRequests.md, mkdocs.yml
Foi criado os documentos de Contribuição na wiki do projeto. Foram adicionadas "Como contribuir?", "Codigo de Conduta" e "Politicas". Esse último contém "Commits", "Branchs", "Issues" e "Pull Requests".
#51 Adicionar Política de Repositório na wiki
Foi testado usando o mkdocs. Todas as mudanças que fizemos foram analisadas e observadas usando o serve criado por ele.
* Criar caminho da "Contribuição" no mkdocs.yml;
* Adicionar arquivos das contribuições na pasta /docs/policies;
* Preencher conteúdo desses arquivos.
=> Política de Repositório

docs/documentacao/documento-de-visao.md, docs/policies/branches.md
O Documento de Visão e o documento de Politica de Branchs foram atualizados e upados na gitpage. 
No Documento de Visão, foram adicionados os tópicos: "Recursos do Produto", "Restrições" e "Requisitos do Produto". Também foram adicionadas as Referencias nesse Doc. Já na política de Repositório das Branchs, foi adicionado um tópico: "document". Foi criado pois não havia uma padronização das branchs de documentação.
#57 Atualizar documento de Visão.
#51 Adicionar Politica de Repositorio na Wiki (Apenas complementa essa issue na verdade).
Foi testado com apoio do mkdocs serve e do Visual Studio (usando o atalho Ctrl + Shift + V, onde conseguimos ter um preview da página).
* Adicionar "Recursos do Produto", "Restrições" e "Requisitos do Produto" ao Documento de Visao
* Adicionar nova linha no …
=> Atualizar Documento de Visao e Politica de Branchs

docs/documentacao/planejamento-de-riscos.md, mkdocs.yml
Esse PR está relacionado a definição do planejamento de Riscos do nosso time, é um documento muito importante pois traz algumas informações de como proceder para evitar alguns riscos que possam vir a ocorrer durante o desenvolvimento do projeto, bem como remediá-los.
#70
Foi utilizado mkdocs e o Visual Studio Code como ferramentas de teste
* Criado e documentado o planejamento de riscos do time.
=> #70 Criando Planejamento de Riscos

docs/produto/prototipos.md
Foi adicionado um tópico para o protótipo de alta fidelidade com um visualizador do projeto que atualiza automaticamente. Além disso também foram atualizadas as descrições das telas da apliacação.
#72 
Com a ferramenta mkdocs.
* Adicionado tópico para Protótipo de Alta Fidelidade
* Atualizadas Descrições de Telas já criadas
* Adicionadas Descrições de Novas Telas.
=> #72 Atualizando Documento de Protótipo

Pipfile, Pipfile.lock, docker-compose.yml, src/app/app.py, src/app/config.py, src/app/ext/auth.py, src/app/ext/cors.py, src/database/database.sql
Flask-JWT, que é uma dependencia para autenticação via token, e as politicas de comunicação entre plataforma (CORS) foram adicionados. Além disso, atualizei o docker para que ocorra o flash reload do flask
#86
* Flask-JWT adicionado
* Flask-cors adicionado
* Docker flask atualizado
=> #86 configurando autenticação

docs/produto/backlog.md
Com o andamento do projeto, notou-se a necessidade de revisar o backlog do produto, descrevendo melhor as funcionalidades e histórias de usuários.
#98 
Utilizando o vscode e mkdocs serve
* Revisado as funcionalidades
* Revisado as histórias de usuários
=> #98 Revisando tópicos do backlog do produto

README.md
Para tornar a primeira impressão do projeto algo mais didático e apresentável o arquivo readme foi revisado.
#96 
Utilizando a própria interface do github
* Revisada a Visão Geral
* Adicionada logo do projeto
* Adicionadas badges
* Guia de instalação para ambos back e front-end
=> #96 Revisar readme

src/app/controller/__init__.py, src/app/controller/login_resources.py, src/app/model/services/login_services.py, src/app/model/services/student_services.py, src/app/view/login_schema.py
Um estudante já criado consegue se autenticar.
#104 
Foi testado juntamente com o [frontend](https://github.com/fga-eps-mds/2020.2-Anunbis-Frontend/tree/feature/%23104-Criando_tela_de_login_aluno)
* Estudante consegue fazer login
=> #104 [US03] Realizar Login Aluno

docs/documentacao/documento-de-arquitetura.md, docs/documentacao/documento-de-visao.md, docs/documentacao/roadmap.md, docs/index.md, docs/sprints/planejamento-sprint-0.md, docs/sprints/planejamento-sprint-1.md, docs/sprints/planejamento-sprint-2.md, docs/sprints/planejamento-sprint-3.md, docs/sprints/planejamento-sprint-4.md, docs/sprints/planejamento-sprint-5.md, docs/sprints/revisao-sprint-0.md, docs/sprints/revisao-sprint-1.md, docs/sprints/revisao-sprint-2.md, docs/sprints/revisao-sprint-3.md, docs/sprints/revisao-sprint-4.md, docs/sprints/revisao-sprint-5.md, docs/sprints/revisao-sprint-template.md, mkdocs.yml
Feita a revisão do roadmap e da aba das sprints na wiki
#100 
Foi testado utilizando o mkdocs e a ide do visual studo code
* Revisada aba das Sprints
* Revisado o Roadmap
=> Document/#100 Revisado Roadmap e aba das sprints

docs/CODE_OF_CONDUCT.md, docs/como_contribuir.md, docs/documentacao/documento-de-arquitetura.md, docs/documentacao/documento-de-metodologias.md, docs/documentacao/documento-de-visao.md, docs/documentacao/planejamento-de-riscos.md, docs/documentacao/roadmap.md, docs/documentacao/termo-de-abertura.md, docs/index.md, docs/policies/branches.md, docs/policies/issues.md, docs/policies/pullRequests.md, docs/produto/backlog.md, docs/produto/prototipos.md, docs/sprints/planejamento-sprint-0.md, docs/sprints/planejamento-sprint-2.md, docs/sprints/planejamento-sprint-3.md, docs/sprints/planejamento-sprint-4.md, docs/sprints/revisao-sprint-0.md, docs/sprints/revisao-sprint-1.md, docs/sprints/revisao-sprint-2.md, docs/sprints/revisao-sprint-3.md, docs/sprints/revisao-sprint-4.md, docs/sprints/revisao-sprint-5.md
Corrigindo erros gramáticos e realizando finais ajustes para a Realease 1
#116 
Utilizando o mkdocs serve e o VSCode
Como foram vários pequenos ajustes é mais fácil rastreá-los pela aba arquivos mudados aqui nesse PR e procurar na wiki usando mkdocs serve nessa branch. Mas aqui estão alguns exemplos:
Adicionando Sprint 6 no Roadmap:
Adicionando Planning Poker ao documento de metodologias
* Revisão da documentação da wiki
=> #116 Revisando documentação da wiki

docs/sprints/planejamento-sprint-7.md, docs/sprints/revisao-sprint-7.md, mkdocs.yml
Foi Documentada a sprint 7 e está aberto o PR afim de obter maiores feedbacks da equipe quanto a veracidade do que foi escrito !
#119 
Por meio do Mkdocs serve.
* Documentado o Planning e Review da Sprint 7
=> Documentando a sprint 7

docs/produto/identidade-visual.md, mkdocs.yml
Era necessário um documento focado em explicar os aspectos visuais de nosso projeto, como suas cores , logo  e principalmente o nome Anunbis.
#121 
Foi testado utilizando o mkdocs serve e o visual studio em uma branch separada para gerar uma wiki local.
Imagem1:
Imagem2:
Imagem3:
#121 Documentar a identidade visual
=> Criação do documento de identidade visual

.env, Pipfile, Pipfile.lock, Procfile, docker-compose.yml, docs/produto/identidade-visual.md, run.py, src/app/config.py, src/app/model/dao/course_dao.py, src/app/model/dao/discipline_dao.py, src/app/model/dao/post_dao.py, src/app/model/dao/professor_dao.py, src/app/model/dao/report_dao.py, src/app/model/dao/student_dao.py, src/app/model/services/login_services.py, src/app/model/services/professor_services.py, src/database/database.sql, src/database/seeds.sql
Foi criado no heroku os seguintes apps [front-end](https://anunbis-frontend.herokuapp.com/) e [backend](http://anunbis-backend.herokuapp.com/anunbis/api/) da nossa aplicação, porém eles estão linkados com os repositórios clonados do Thiago, então o deploy só acontecerá se as mudanças forem sentidas nesse repositório específico.
#148
Foi testado utilizando a própria aplicação no heroku, além do software DBeaver para avaliar o Banco de dados e suas tabelas, testes estes feito em pareamento.
* Deploy da aplicação no heroku
* Utilização do postgresql como BD por conta da sua gratuidade em relação ao mysql
* Refatoração das tabelas do BD
=> Configurando deploy da aplicação no heroku

docs/sprints/planejamento-sprint-8.md, docs/sprints/revisao-sprint-8.md, mkdocs.yml
Foi documentado em nossa wiki a sprint 8, com seu planejamento e revisão, é interessante avaliarem a revisão para ver se estão de acordo.
#151 
Por meio do mkdocs.
* Documentado o planejamento da sprint 8
* Documentado a revisão da sprint 8
=> Documentação da Sprint 8

app/controller/course_resources.py, app/controller/post_resources.py, app/controller/professor_resources.py
Algumas rotas foram restringidas para serem acessadas apenas com token
#154 
* Rota /professor/%nome_professor% restringida
* Rota /post restringida
=> #154 Autenticando rotas

.github/workflows/main.yml
Automatizei os Testes de Integração pra rodar sempre que alguem fizer um PullRequest. Além disso, as estátisticas estão sendo enviadas para o Coveralls
#161 
Fiz os testes no meu fork para nao poluir este repositorio. Veja o [PR](https://github.com/thiagohdaqw/2020.2-Anunbis-Testes/pull/6) para ver funcionando.
* Automatizando testes do Pull Request
* Enviando dados para o Coveralls
=> #161 Testes no GitHub Actions

docs/documentacao/documento-de-visao.md
Foi refatorado nosso documento de visão a fim de demonstrar de melhor maneira aspectos como visão geral do produto, descrição dos envolvidos e usuários do projeto, além de passar maior fidelidade e clareza sobre o que pretendemos com esse projeto.
#123
Utilizando a ferramenta do mkdocs serve e a extensão [code spell checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-portuguese) presente no vscode para verificação de erros ortográficos. 
O mais interessante para quem está avaliando seria a leitura dos aspectos gerais das mudanças, pois seriam muitas capturas de tela para cobrir tanto conteúdo.
* Refatorado parte de descrição dos usuários e envolvidos e da visão geral do produto
* Revisado parte de introdução, posicionamento e requisitos.
* …
=> Refatorando Documento de Visão

app/controller/student_resources.py, app/model/dao/post_dao.py, app/model/dao/student_dao.py, app/model/entity/student.py, app/model/services/student_services.py, tests/tests_post.py, tests/tests_student.py
Adicionei as rotas e testes para que um aluno consiga excluir sua própria conta.
Os testes unitários foram implementados e testado juntamente com o frontend.
* Rota /student/<int:reg_student> criada com o metodo DELETE 
* Validando se o token de quem chamou é mesmo do aluno que vai ser deletado
* Testes de integração
=> #142 [US24] Aluno excluir sua conta

app/controller/student_resources.py, app/model/dao/student_dao.py, app/model/services/student_services.py, tests/tests_student.py
Foi feita no back-end as rotas e métodos necessários para possibilitar a modificação de senha dos alunos.
#140 
Foi testado utilizando o postman com as novas rotas, testes de integração e pareamento junto ao front-end.
* Criação do método de modificação de senha e sua rota
* Adição dos testes referentes a modificação de senha
=> [US22] Modificar senha do aluno

app/controller/post_resources.py, app/controller/professor_resources.py, app/model/post.py, app/model/student.py, app/schemas/post_schema.py, app/schemas/professor_schema.py, app/schemas/student_schema.py, app/services/post_services.py, tests/tests_post.py, tests/tests_professor.py, tests/tests_student.py
Criação da feature relacionada com concordar ou discordar da avaliação de outros alunos
#137 
Foi testado utilizando o back end com o docker e o front end com o npm, além do visual studio e localhost
imagem1:
imagem2:
Estudante concordar e discordar de comentários
=> [US19] Feature/#137 avaliar comentario de terceiros

docs/sprints/planejamento-sprint-9.md, docs/sprints/revisao-sprint-9.md, mkdocs.yml
Foi documentado em nossa wiki a sprint 9, com seu planejamento e revisão, é interessante avaliarem a revisão para ver se estão de acordo com o que foi escrito !
#174 
Por meio do mkdocs serve.
* Documentado o planejamento da sprint 9
* Documentado a revisão da sprint 9
=> Documentação da sprint 9

docs/sprints/planejamento-sprint-10.md, docs/sprints/revisao-sprint-10.md, mkdocs.yml
Foi documentado em nossa wiki a sprint 10, que foi bem atípica, então é interessante avaliarem a revisão para ver se estão de acordo com o que foi escrito ou se há alguma melhoria que pode ser sugerida !
#179 
Por meio do mkdocs serve.
* Planejamento da sprint 10
* Revisão e retrospectiva da sprint 10
=> Documentação da Sprint 10

app/controller/professor_resources.py, app/schemas/professor_schema.py, app/services/professor_services.py, tests/tests_professor.py
Por conta dos botões de concordo e discordo não estarem sendo atualizados no frontend, por que estava sendo feita somente uma requisição para o back, foi necessário mudar o get dos professores, que agora não vem com os posts, então criamos outro get para esse caso, que buscamos o professor pelo id_professor e retorna os dados necessários para a pesquisa de professor e seus posts. Dessa forma, realiza uma requisição a cada click nas box de professores.
#180
Os testes unitários foram implementados e testado juntamente com o frontend.
* Rota /professor/<int:id> criada com o metodo get professor por id_professor
* Testes de integração
=> #180 Melhorando a pesquisa de professor

docs/documentacao/planejamento-de-riscos.md
Nesse pull request foi criado o Burndown de Riscos na wiki, adicionando uma tabela para representar melhor nossos riscos durante as sprints.
Criação do gráfico dos riscos no drive. Descrição melhor do burndown na aba 'planejamento de riscos' da wiki.
[#185](https://github.com/fga-eps-mds/2020.2-Anunbis/issues/185)
Foi testado com mkdocs e google drive.
* Criação do documento de gerenciamento de riscos no drive;
* Criação do tópico de Burndown na página de 'planejamento de riscos' na wiki;
* Importação do gráfico de riscos para wiki.
=> Burndown de Riscos

tests/tests_post.py
Como o get do PostList pode pegar tanto posts do usuário aluno, como sobre o usuário professor, para o segundo caso só foi preciso realizar os testes.
#136
Através do docker-compose up e pipenv run bash tests.sh para visualizar a cobertura dos testes
* Todos os testes do get do PostList realizados
=> #136 Adicionando testes do get do PostList para usuario professor

app/schemas/post_schema.py
Adicionando rating no post_schema
#209
npm e docker
* Atributo rating vem quando faço a requisição de posts do professor
=> (#209) Corrigindo bug da tela inicial do professor

app/model/professor.py, app/model/user.py, app/services/professor_services.py
Para preparar pra release 2, passei o pente fino e arrumei 2 bugs. O primeiro, quando voce exclui o professor, a verificacao de email e a senha nao sao apagadas. O segundo, fiz a limpeza do nome do professor na hora do cadastro.
#224
* Email_verified e senha estao sendo apagados quando voce exclui um professor
* Retirando espaços do nome do professor na hora do cadastro
=> #224 Bugfix final para Release 2

docs/post_mortem.md, mkdocs.yml
A fim de finalização do projeto, foi documentado nosso post mortem feito em equipe
#219 
Por meio do mkdocs e pareamento.
* Documentado o post mortem na wiki
=> Documentando o post mortem

README.md
Colocando os arquivos dos slides e o vídeo da apresentação da R2
#220 
* Adicionado os links dos arquivos da apresentação da R2
=> (#220) Adicionando video e slides da Release 2
